name: Publish to GitHub Packages

on:
  workflow_dispatch:

jobs:
  publish-github:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 'lts/*'
          registry-url: 'https://npm.pkg.github.com'
      - run: npm install
      - run: |
          npm pkg set name='@dermalytics-dev/dermalytics'
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
